   # Factorización $LDL^T$
   
   para matrices simetricas invertibles

In [1]:
[[3 -3 3];[-3 5 1];[3 1 10]]

3×3 Array{Int64,2}:
  3  -3   3
 -3   5   1
  3   1  10

In [2]:
A = Array{Float64}([[3 -3 3];[-3 5 1];[3 1 10]])

3×3 Array{Float64,2}:
  3.0  -3.0   3.0
 -3.0   5.0   1.0
  3.0   1.0  10.0

In [3]:
?lu

search: lu lufact lufact! flush ClusterManager values include include_string



```
lu(A, pivot=Val{true}) -> L, U, p
```

Compute the LU factorization of `A`, such that `A[p,:] = L*U`. By default, pivoting is used. This can be overridden by passing `Val{false}` for the second argument.

See also [`lufact`](@ref).

# Example

```jldoctest
julia> A = [4. 3.; 6. 3.]
2×2 Array{Float64,2}:
 4.0  3.0
 6.0  3.0

julia> L, U, p = lu(A)
([1.0 0.0; 0.666667 1.0], [6.0 3.0; 0.0 1.0], [2, 1])

julia> A[p, :] == L * U
true
```


In [4]:
L,U = lu(A, Val{false});

In [5]:
L

3×3 Array{Float64,2}:
  1.0  0.0  0.0
 -1.0  1.0  0.0
  1.0  2.0  1.0

In [6]:
U

3×3 Array{Float64,2}:
 3.0  -3.0   3.0
 0.0   2.0   4.0
 0.0   0.0  -1.0

In [7]:
d = diag(U)

3-element Array{Float64,1}:
  3.0
  2.0
 -1.0

In [8]:
D = diagm(d)

3×3 Array{Float64,2}:
 3.0  0.0   0.0
 0.0  2.0   0.0
 0.0  0.0  -1.0

In [9]:
D⁻¹ = diagm(1.0./d)

3×3 Array{Float64,2}:
 0.333333  0.0   0.0
 0.0       0.5   0.0
 0.0       0.0  -1.0

In [10]:
D⁻¹*U

3×3 Array{Float64,2}:
 1.0  -1.0  1.0
 0.0   1.0  2.0
 0.0   0.0  1.0

In [35]:
L'

3×3 Array{Float64,2}:
 1.0  -1.0  1.0
 0.0   1.0  2.0
 0.0   0.0  1.0

In [11]:
D⁻¹*U == L'

true

In [12]:
L*D*L'

3×3 Array{Float64,2}:
  3.0  -3.0   3.0
 -3.0   5.0   1.0
  3.0   1.0  10.0

In [13]:
A

3×3 Array{Float64,2}:
  3.0  -3.0   3.0
 -3.0   5.0   1.0
  3.0   1.0  10.0

In [14]:
L*D*L' == A

true

# Factorización LU via `lufact`

In [39]:
?lufact

search: lufact lufact!



```
lufact(A [,pivot=Val{true}]) -> F::LU
```

Compute the LU factorization of `A`.

In most cases, if `A` is a subtype `S` of `AbstractMatrix{T}` with an element type `T` supporting `+`, `-`, `*` and `/`, the return type is `LU{T,S{T}}`. If pivoting is chosen (default) the element type should also support `abs` and `<`.

The individual components of the factorization `F` can be accessed by indexing:

| Component | Description                         |
|:--------- |:----------------------------------- |
| `F[:L]`   | `L` (lower triangular) part of `LU` |
| `F[:U]`   | `U` (upper triangular) part of `LU` |
| `F[:p]`   | (right) permutation `Vector`        |
| `F[:P]`   | (right) permutation `Matrix`        |

The relationship between `F` and `A` is

`F[:L]*F[:U] == A[F[:p], :]`

`F` further supports the following functions:

| Supported function  | `LU` | `LU{T,Tridiagonal{T}}` |
|:------------------- |:---- |:---------------------- |
| [`/`](@ref)         | ✓    |                        |
| [`\`](@ref)         | ✓    | ✓                      |
| [`cond`](@ref)      | ✓    |                        |
| [`inv`](@ref)       | ✓    | ✓                      |
| [`det`](@ref)       | ✓    | ✓                      |
| [`logdet`](@ref)    | ✓    | ✓                      |
| [`logabsdet`](@ref) | ✓    | ✓                      |
| [`size`](@ref)      | ✓    | ✓                      |

# Example

```jldoctest
julia> A = [4 3; 6 3]
2×2 Array{Int64,2}:
 4  3
 6  3

julia> F = lufact(A)
Base.LinAlg.LU{Float64,Array{Float64,2}} with factors L and U:
[1.0 0.0; 1.5 1.0]
[4.0 3.0; 0.0 -1.5]

julia> F[:L] * F[:U] == A[F[:p], :]
true
```

```
lufact(A::SparseMatrixCSC) -> F::UmfpackLU
```

Compute the LU factorization of a sparse matrix `A`.

For sparse `A` with real or complex element type, the return type of `F` is `UmfpackLU{Tv, Ti}`, with `Tv` = [`Float64`](@ref) or `Complex128` respectively and `Ti` is an integer type ([`Int32`](@ref) or [`Int64`](@ref)).

The individual components of the factorization `F` can be accessed by indexing:

| Component | Description                         |
|:--------- |:----------------------------------- |
| `F[:L]`   | `L` (lower triangular) part of `LU` |
| `F[:U]`   | `U` (upper triangular) part of `LU` |
| `F[:p]`   | right permutation `Vector`          |
| `F[:q]`   | left permutation `Vector`           |
| `F[:Rs]`  | `Vector` of scaling factors         |
| `F[:(:)]` | `(L,U,p,q,Rs)` components           |

The relation between `F` and `A` is

`F[:L]*F[:U] == (F[:Rs] .* A)[F[:p], F[:q]]`

`F` further supports the following functions:

  * [`\`](@ref)
  * [`cond`](@ref)
  * [`det`](@ref)

!!! note
    `lufact(A::SparseMatrixCSC)` uses the UMFPACK library that is part of SuiteSparse. As this library only supports sparse matrices with [`Float64`](@ref) or `Complex128` elements, `lufact` converts `A` into a copy that is of type `SparseMatrixCSC{Float64}` or `SparseMatrixCSC{Complex128}` as appropriate.



In [15]:
F = lufact(A, Val{false});

In [16]:
F[:L]

3×3 Array{Float64,2}:
  1.0  0.0  0.0
 -1.0  1.0  0.0
  1.0  2.0  1.0

In [19]:
L

3×3 Array{Float64,2}:
  1.0  0.0  0.0
 -1.0  1.0  0.0
  1.0  2.0  1.0

In [17]:
F[:U]

3×3 Array{Float64,2}:
 3.0  -3.0   3.0
 0.0   2.0   4.0
 0.0   0.0  -1.0

In [20]:
U

3×3 Array{Float64,2}:
 3.0  -3.0   3.0
 0.0   2.0   4.0
 0.0   0.0  -1.0

In [21]:
F[:P]

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

**Por defecto `lufact`realiza pivoteo**

In [25]:
F₂ = lufact(A);
F₂[:P]

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  0.0  1.0
 0.0  1.0  0.0

 # Factorización de Cholesky

In [2]:
?chol

search: chol cholfact cholfact! searchsortedlast CachingPool chop chown chomp



```
chol(A) -> U
```

Compute the Cholesky factorization of a positive definite matrix `A` and return the [`UpperTriangular`](@ref) matrix `U` such that `A = U'U`.

# Example

```jldoctest
julia> A = [1. 2.; 2. 50.]
2×2 Array{Float64,2}:
 1.0   2.0
 2.0  50.0

julia> U = chol(A)
2×2 UpperTriangular{Float64,Array{Float64,2}}:
 1.0  2.0
  ⋅   6.78233

julia> U'U
2×2 Array{Float64,2}:
 1.0   2.0
 2.0  50.0
```

```
chol(x::Number) -> y
```

Compute the square root of a non-negative number `x`.

# Example

```jldoctest
julia> chol(16)
4.0
```


In [5]:
A = randn(5,3);
B = A'A

3×3 Array{Float64,2}:
  2.76178   -0.404342   0.635005
 -0.404342   8.20569   -0.617677
  0.635005  -0.617677   2.01236 

In [8]:
L = chol(B)'

3×3 LowerTriangular{Float64,Array{Float64,2}}:
  1.66186     ⋅         ⋅     
 -0.243307   2.85421    ⋅     
  0.382105  -0.183837  1.35372

In [10]:
L*L'

3×3 Array{Float64,2}:
  2.76178   -0.404342   0.635005
 -0.404342   8.20569   -0.617677
  0.635005  -0.617677   2.01236 

In [35]:
A₂ = [1.0 2.0; 2.0 4.0];
B₂ = A₂'A₂

2×2 Array{Float64,2}:
  5.0  10.0
 10.0  20.0

In [36]:
L₂ = chol(B₂)'

LoadError: Base.LinAlg.PosDefException(2)

In [4]:
?cholfact

search: cholfact cholfact!



```
cholfact(A, [uplo::Symbol,] Val{false}) -> Cholesky
```

Compute the Cholesky factorization of a dense symmetric positive definite matrix `A` and return a `Cholesky` factorization. The matrix `A` can either be a [`Symmetric`](@ref) or [`Hermitian`](@ref) `StridedMatrix` or a *perfectly* symmetric or Hermitian `StridedMatrix`. In the latter case, the optional argument `uplo` may be `:L` for using the lower part or `:U` for the upper part of `A`. The default is to use `:U`. The triangular Cholesky factor can be obtained from the factorization `F` with: `F[:L]` and `F[:U]`. The following functions are available for `Cholesky` objects: [`size`](@ref), [`\`](@ref), [`inv`](@ref), and [`det`](@ref). A `PosDefException` exception is thrown in case the matrix is not positive definite.

# Example

```jldoctest
julia> A = [4. 12. -16.; 12. 37. -43.; -16. -43. 98.]
3×3 Array{Float64,2}:
   4.0   12.0  -16.0
  12.0   37.0  -43.0
 -16.0  -43.0   98.0

julia> C = cholfact(A)
Base.LinAlg.Cholesky{Float64,Array{Float64,2}} with factor:
[2.0 6.0 -8.0; 0.0 1.0 5.0; 0.0 0.0 3.0]

julia> C[:U]
3×3 UpperTriangular{Float64,Array{Float64,2}}:
 2.0  6.0  -8.0
  ⋅   1.0   5.0
  ⋅    ⋅    3.0

julia> C[:L]
3×3 LowerTriangular{Float64,Array{Float64,2}}:
  2.0   ⋅    ⋅
  6.0  1.0   ⋅
 -8.0  5.0  3.0

julia> C[:L] * C[:U] == A
true
```

```
cholfact(A, [uplo::Symbol,] Val{true}; tol = 0.0) -> CholeskyPivoted
```

Compute the pivoted Cholesky factorization of a dense symmetric positive semi-definite matrix `A` and return a `CholeskyPivoted` factorization. The matrix `A` can either be a [`Symmetric`](@ref) or [`Hermitian`](@ref) `StridedMatrix` or a *perfectly* symmetric or Hermitian `StridedMatrix`. In the latter case, the optional argument `uplo` may be `:L` for using the lower part or `:U` for the upper part of `A`. The default is to use `:U`. The triangular Cholesky factor can be obtained from the factorization `F` with: `F[:L]` and `F[:U]`. The following functions are available for `PivotedCholesky` objects: [`size`](@ref), [`\`](@ref), [`inv`](@ref), [`det`](@ref), and [`rank`](@ref). The argument `tol` determines the tolerance for determining the rank. For negative values, the tolerance is the machine precision.

```
cholfact(A; shift = 0.0, perm = Int[]) -> CHOLMOD.Factor
```

Compute the Cholesky factorization of a sparse positive definite matrix `A`. `A` must be a [`SparseMatrixCSC`](@ref) or a [`Symmetric`](@ref)/[`Hermitian`](@ref) view of a `SparseMatrixCSC`. Note that even if `A` doesn't have the type tag, it must still be symmetric or Hermitian. A fill-reducing permutation is used. `F = cholfact(A)` is most frequently used to solve systems of equations with `F\b`, but also the methods [`diag`](@ref), [`det`](@ref), and [`logdet`](@ref) are defined for `F`. You can also extract individual factors from `F`, using `F[:L]`. However, since pivoting is on by default, the factorization is internally represented as `A == P'*L*L'*P` with a permutation matrix `P`; using just `L` without accounting for `P` will give incorrect answers. To include the effects of permutation, it's typically preferable to extract "combined" factors like `PtL = F[:PtL]` (the equivalent of `P'*L`) and `LtP = F[:UP]` (the equivalent of `L'*P`).

Setting the optional `shift` keyword argument computes the factorization of `A+shift*I` instead of `A`. If the `perm` argument is nonempty, it should be a permutation of `1:size(A,1)` giving the ordering to use (instead of CHOLMOD's default AMD ordering).

!!! note
    This method uses the CHOLMOD library from SuiteSparse, which only supports doubles or complex doubles. Input matrices not of those element types will be converted to `SparseMatrixCSC{Float64}` or `SparseMatrixCSC{Complex128}` as appropriate.

    Many other functions from CHOLMOD are wrapped but not exported from the `Base.SparseArrays.CHOLMOD` module.



In [37]:
M = [4. 12. -16.; 12. 37. -43.; -16. -43. 98.]

3×3 Array{Float64,2}:
   4.0   12.0  -16.0
  12.0   37.0  -43.0
 -16.0  -43.0   98.0

In [38]:
C = cholfact(M);
C[:L]

3×3 LowerTriangular{Float64,Array{Float64,2}}:
  2.0   ⋅    ⋅ 
  6.0  1.0   ⋅ 
 -8.0  5.0  3.0

In [39]:
C[:L]*C[:L]'

3×3 Array{Float64,2}:
   4.0   12.0  -16.0
  12.0   37.0  -43.0
 -16.0  -43.0   98.0

In [40]:
y = C[:L]\ones(3)
x = C[:L]'\y

3-element Array{Float64,1}:
  37.9167 
 -10.3333 
   1.66667

In [41]:
M\ones(3)

3-element Array{Float64,1}:
  37.9167 
 -10.3333 
   1.66667