# <font color=blue >Condicionamiento </font>

In [1]:
function T(n::Int64)
    A = Tridiagonal(-ones(n-1),2.0ones(n),-ones(n-1))
    A[1,1] = 1.0
    return A
end

T (generic function with 1 method)

In [2]:
n = 5; T(n)

5×5 Tridiagonal{Float64}:
  1.0  -1.0    ⋅     ⋅     ⋅ 
 -1.0   2.0  -1.0    ⋅     ⋅ 
   ⋅   -1.0   2.0  -1.0    ⋅ 
   ⋅     ⋅   -1.0   2.0  -1.0
   ⋅     ⋅     ⋅   -1.0   2.0

**Halla inversa via factorización LU**

In [3]:
lufact(T(n))\eye(n)

5×5 Array{Float64,2}:
 5.0  4.0  3.0  2.0  1.0
 4.0  4.0  3.0  2.0  1.0
 3.0  3.0  3.0  2.0  1.0
 2.0  2.0  2.0  2.0  1.0
 1.0  1.0  1.0  1.0  1.0

** ¿rutina para la matriz inversa? **

In [5]:
collect(n:-1:1)

5-element Array{Int64,1}:
 5
 4
 3
 2
 1

In [7]:
ones(n)'

1×5 RowVector{Float64,Array{Float64,1}}:
 1.0  1.0  1.0  1.0  1.0

In [8]:
collect(n:-1:1)*ones(n)'

5×5 Array{Float64,2}:
 5.0  5.0  5.0  5.0  5.0
 4.0  4.0  4.0  4.0  4.0
 3.0  3.0  3.0  3.0  3.0
 2.0  2.0  2.0  2.0  2.0
 1.0  1.0  1.0  1.0  1.0

In [9]:
Symmetric( collect(n:-1:1)*ones(n)', :L )

5×5 Symmetric{Float64,Array{Float64,2}}:
 5.0  4.0  3.0  2.0  1.0
 4.0  4.0  3.0  2.0  1.0
 3.0  3.0  3.0  2.0  1.0
 2.0  2.0  2.0  2.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [10]:
function T⁻¹(n::Int64)
    A = Symmetric( collect(n:-1:1)*ones(n)', :L )
    return A
end

T⁻¹ (generic function with 1 method)

In [11]:
T⁻¹(5)

5×5 Symmetric{Float64,Array{Float64,2}}:
 5.0  4.0  3.0  2.0  1.0
 4.0  4.0  3.0  2.0  1.0
 3.0  3.0  3.0  2.0  1.0
 2.0  2.0  2.0  2.0  1.0
 1.0  1.0  1.0  1.0  1.0

**Normas Matriciales de T y su inversa**

In [12]:
T(5)

5×5 Tridiagonal{Float64}:
  1.0  -1.0    ⋅     ⋅     ⋅ 
 -1.0   2.0  -1.0    ⋅     ⋅ 
   ⋅   -1.0   2.0  -1.0    ⋅ 
   ⋅     ⋅   -1.0   2.0  -1.0
   ⋅     ⋅     ⋅   -1.0   2.0

In [28]:
n = 5
Tn = T(n)
n∞T = maximum(sum(abs.(Tn),1))
println("||T||oo = $n∞T")

||T||oo = 4.0


In [29]:
maximum(sum(abs.(Tn),2)) == norm(Tn,Inf)

true

In [17]:
T⁻¹(5)

5×5 Symmetric{Float64,Array{Float64,2}}:
 5.0  4.0  3.0  2.0  1.0
 4.0  4.0  3.0  2.0  1.0
 3.0  3.0  3.0  2.0  1.0
 2.0  2.0  2.0  2.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [18]:
n∞T⁻¹ = norm(T⁻¹(n),Inf)
println("||inv(T)||oo = $n∞T⁻¹")

||inv(T)||oo = 15.0


** Número de Condición**

In [19]:
κ∞T = n∞T*n∞T⁻¹
println("cond(T,∞) = $κ∞T")

cond(T,∞) = 60.0


In [20]:
cond(Tn,Inf)

60.0

*Otro Ejemplo*

In [22]:
L = tril(ones(5,5))

5×5 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0
 1.0  1.0  0.0  0.0  0.0
 1.0  1.0  1.0  0.0  0.0
 1.0  1.0  1.0  1.0  0.0
 1.0  1.0  1.0  1.0  1.0

In [23]:
cond(L,Inf)

9.333333333333334

Sin embargo $$\text{cond}_\infty(L)=10$$

<font color=red> ADVERTENCIA</font>: La rutina `cond( )` de Julia estima el  número de
condición. 

Esta rutina da cotas inferiores para `cond(A,1)` y `cond(A,Inf)` 

In [74]:
?cond

search: cond condskeel Condition macroexpand @macroexpand checkbounds conv conj



```
cond(M, p::Real=2)
```

Condition number of the matrix `M`, computed using the operator `p`-norm. Valid values for `p` are `1`, `2` (default), or `Inf`.


**Condicionamiento y Determinante**

In [35]:
function B(n::Int64)
    A = triu(-ones(n,n))
    [A[i,i] = 1.0 for i∈ 1:n]
    return A
end

B (generic function with 1 method)

In [49]:
m = 20
Bm = B(m)

20×20 Array{Float64,2}:
 1.0  -1.0  -1.0  -1.0  -1.0  -1.0  …  -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 0.0   1.0  -1.0  -1.0  -1.0  -1.0     -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 0.0   0.0   1.0  -1.0  -1.0  -1.0     -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 0.0   0.0   0.0   1.0  -1.0  -1.0     -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 0.0   0.0   0.0   0.0   1.0  -1.0     -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 0.0   0.0   0.0   0.0   0.0   1.0  …  -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 0.0   0.0   0.0   0.0   0.0   0.0     -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 0.0   0.0   0.0   0.0   0.0   0.0     -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 0.0   0.0   0.0   0.0   0.0   0.0     -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 0.0   0.0   0.0   0.0   0.0   0.0     -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 0.0   0.0   0.0   0.0   0.0   0.0  …  -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 0.0   0.0   0.0   0.0   0.0   0.0     -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 0.0   0.0   0.0   0.0   0.0   0.0     -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 0.0   0.0   0

In [50]:
Bim =inv(B(m))

20×20 Array{Float64,2}:
 1.0  1.0  2.0  4.0  8.0  16.0  32.0  64.0  …  65536.0  131072.0  262144.0
 0.0  1.0  1.0  2.0  4.0   8.0  16.0  32.0     32768.0   65536.0  131072.0
 0.0  0.0  1.0  1.0  2.0   4.0   8.0  16.0     16384.0   32768.0   65536.0
 0.0  0.0  0.0  1.0  1.0   2.0   4.0   8.0      8192.0   16384.0   32768.0
 0.0  0.0  0.0  0.0  1.0   1.0   2.0   4.0      4096.0    8192.0   16384.0
 0.0  0.0  0.0  0.0  0.0   1.0   1.0   2.0  …   2048.0    4096.0    8192.0
 0.0  0.0  0.0  0.0  0.0   0.0   1.0   1.0      1024.0    2048.0    4096.0
 0.0  0.0  0.0  0.0  0.0   0.0   0.0   1.0       512.0    1024.0    2048.0
 0.0  0.0  0.0  0.0  0.0   0.0   0.0   0.0       256.0     512.0    1024.0
 0.0  0.0  0.0  0.0  0.0   0.0   0.0   0.0       128.0     256.0     512.0
 0.0  0.0  0.0  0.0  0.0   0.0   0.0   0.0  …     64.0     128.0     256.0
 0.0  0.0  0.0  0.0  0.0   0.0   0.0   0.0        32.0      64.0     128.0
 0.0  0.0  0.0  0.0  0.0   0.0   0.0   0.0        16.0      32.0      64.0
 

In [51]:
κ∞B = norm(Bm,Inf)*norm(Bim,Inf)
println("cond(Bm,Inf) = $κ∞B")
println("m x 2^(m-1) = $(m*2^(m-1))")

cond(Bm,Inf) = 1.048576e7
m x 2^(m-1) = 10485760


In [52]:
det(Bm)

1.0

In [30]:
A₂ =collect(7:-1:1)*ones(7)'

7×7 Array{Float64,2}:
 7.0  7.0  7.0  7.0  7.0  7.0  7.0
 6.0  6.0  6.0  6.0  6.0  6.0  6.0
 5.0  5.0  5.0  5.0  5.0  5.0  5.0
 4.0  4.0  4.0  4.0  4.0  4.0  4.0
 3.0  3.0  3.0  3.0  3.0  3.0  3.0
 2.0  2.0  2.0  2.0  2.0  2.0  2.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [31]:
maximum(sum(abs.(A₂),1)) 

28.0

In [32]:
maximum(sum(abs.(A₂),1))  == norm(A₂,1)

true

In [33]:
maximum(sum(abs.(A₂),2)) 

49.0

In [34]:
maximum(sum(abs.(A₂),2)) == norm(A₂,Inf)

true